module.exports = {
	coffee: 'text/javascript',
	css: 'text/css',
	gif: 'image/gif',
	htm: 'text/html',
	html: 'text/html',
	ico: 'image/x-icon',
	jade: 'text/jade',
	jpg: 'image/jpg',
	jpeg: 'image/jpg',
	js: 'text/javascript',
	json: 'text/json',
	less: 'text/css',
	md: 'text/markdown',
	png: 'image/png',
	sass: 'text/css',
	sql: 'text/sql',
	txt: 'text/plain',
	xml: 'text/xml'
};